### ISSUE TITLE
Fix sidebar hovering over content

### ISSUE THREAD

**Issue by YakovL** [jehy/mami#3]
As is (including in Chrome; depends on zoom level, though):
![image](https://user-images.githubusercontent.com/1131924/45551714-70347c00-b837-11e8-8349-4299f97095ea.png)
![image](https://user-images.githubusercontent.com/1131924/45551735-7c203e00-b837-11e8-83d5-ffdae0915223.png)

Possible fix: add `col-xs-3` class to the sidebar as well:

![image](https://user-images.githubusercontent.com/1131924/45551910-efc24b00-b837-11e8-8dae-585a8d5104a2.png)

**Comment by jehy** [comment]
Не смог воспроизвести, но предложенный фикс применил - хуже он точно не делает. А что - в этом семестре кто-то читает по моим материалам? : )

**Comment by YakovL** [comment]
Не знаю, я в МАМИ не учусь, просто раскладывал некоторые из собранных ссылок по security по "разделам". К слову, можно ещё одно issue открыть под это дело: было бы удобнее, если бы в [индексе](https://jehy.github.io/mami/) лабы были не только пронумерованы, но и в скобках указаны темы

**Comment by jehy** [comment]
Да, отличная мысль!
