### ISSUE TITLE
Добавить в оглавлении названия (темы) лаб

### ISSUE THREAD

**Issue by YakovL** [jehy/mami#5]
Было бы удобно, если бы в [оглавлении](https://jehy.github.io/mami/) лабы были не только пронумерованы, но и были отмечены их темы – особенно когда ищешь конкретную

**Comment by YakovL** [comment]
Хм, не знаю почему, но https://jehy.github.io/mami/ мне по-прежнему показывает старый список:

![image](https://user-images.githubusercontent.com/1131924/45619301-74ec7080-ba81-11e8-9965-55b931f54aa6.png)

хотя на страницах лаб отображается новый заголовок:

![image](https://user-images.githubusercontent.com/1131924/45619324-8b92c780-ba81-11e8-975e-c834f00cf848.png)

**Comment by jehy** [comment]
Ага, забыл ребилд сделать. Готово.
